export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCESS = "GET_TODO_SUCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";



export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCESS = "ADD_TODO_SUCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";



export const TOGGLE_TODO_REQUEST = "TOGGLE_TODO_REQUEST";
export const TOGGLE_TODO_SUCESS = "TOGGLE_TODO_SUCESS";
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE";


export const REMOVE_TODO_REQUEST = "REMOVE_TODO_REQUEST";
export const REMOVE_TODO_SUCESS = "REMOVE_TODO_SUCESS";
export const REMOVE_TODO_FAILURE = "REMOVE_TODO_FAILURE";